# Generated by Django 4.0.3 on 2022-03-07 01:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionApp',
            fields=[
                ('institution_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('social_reasons', models.CharField(max_length=100)),
                ('nit', models.CharField(max_length=12, unique=True)),
                ('website', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('legal_representative_name', models.CharField(max_length=100)),
                ('legal_representative_document', models.CharField(max_length=100)),
                ('token', models.CharField(blank=True, max_length=560)),
                ('avatar', models.CharField(blank=True, max_length=500)),
                ('register_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HeadquartersInstitutionApp',
            fields=[
                ('Headquarters_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('direction', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('register_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('institution_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.institutionapp')),
            ],
        ),
    ]
