# Generated by Django 4.0.3 on 2022-03-07 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupTypeUserApp',
            fields=[
                ('ma_grouptype_user_id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='TypeUserApp',
            fields=[
                ('ma_type_user_id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('token', models.TextField(blank=True, null=True)),
                ('ma_grouptype_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.grouptypeuserapp')),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='UserApp',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('names', models.CharField(max_length=30)),
                ('lastnames', models.CharField(max_length=30)),
                ('document', models.CharField(max_length=12, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=250)),
                ('token', models.CharField(blank=True, max_length=560)),
                ('token_operation', models.CharField(blank=True, max_length=560)),
                ('avatar', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=0)),
                ('ma_type_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.typeuserapp')),
            ],
        ),
    ]
