# Generated by Django 4.0.3 on 2022-03-09 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userapp_ma_type_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typeuserapp',
            options={},
        ),
        migrations.AlterField(
            model_name='userapp',
            name='ma_type_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.typeuserapp'),
        ),
    ]
