# Generated by Django 4.0.3 on 2022-03-09 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_typeuserapp_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typeuserapp',
            options={'ordering': ['label']},
        ),
    ]
