# Generated by Django 4.0.3 on 2022-03-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_typeuserapp_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeuserapp',
            name='label',
            field=models.CharField(blank=True, default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='typeuserapp',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre'),
        ),
    ]
